server:
  port: 6666

STRIPE_SECRET_KEY : sk_test_51J6D6HSE12uH2wFRE5cMBNvYf38lPYMjzHkcAkyWJnB1CmjGwDcUwLmNgcuonLxcoeTuBgKcJO94hzH5lqZ6nCxD00Xelg1nqD
STRIPE_PUBLIC_KEY  : pk_test_51J6D6HSE12uH2wFR6Vf84axWFb1rVxhm8h5foDR6qTyiBOP6Eb7YLlRvoCNVlzI6Y0lQfvJBpix4BDVXLuk7OjEP00vKR9vcIA
